# Generated by Django 2.2.7 on 2020-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=50)),
                ('cpf', models.IntegerField(max_length=11)),
                ('matricula', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
